repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: black
          name: black
          entry: poetry run black zerohero/ tests/
          language: system
          always_run: true
          pass_filenames: false
        - id: pylint
          name: pylint
          entry: poetry run pylint zerohero/* tests/*
          language: system
          always_run: true
          pass_filenames: false
